[package]
name = "wesl-c"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
wesl = { workspace = true }

[lints]
workspace = true

[features]
eval = ["wesl/eval"]
generics = ["wesl/generics"]
