[workspace]
members = ["crates/wgsl-parse", "crates/wesl-macros", "crates/wesl", "crates/wesl-test", "crates/wesl-web", "examples/wesl-random", "examples/wesl-consumer"]

[workspace.package]
version = "0.1.1"
edition = "2021"
authors = ["Mathis Brossier <mathis.brossier@gmail.com>"]
repository = "https://github.com/wgsl-tooling-wg/wesl-rs"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
wgsl-parse = { path = "crates/wgsl-parse", version = "0.1.1" }
wesl = { path = "crates/wesl", version = "0.1.1" }
wesl-macros = { path = "crates/wesl-macros", version = "0.1.1" }

[package]
name = "wesl-cli"
description = "Various tools to parse, verify, evaluate and modify wgsl shader source."
documentation = "https://docs.rs/wesl-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
clap = { version = "4.5.11", features = ["derive"] }
wgsl-parse = { workspace = true }
wesl = { workspace = true, features = ["eval", "generics", "package"] }
thiserror = "2.0.11"
naga = { version = "24.0.0", optional = true, features = ["wgsl-in"] }

[[bin]]
name = "wesl"
path = "src/main.rs"

[features]
default = ["naga"]
