[package]
name = "wesl"
version = "0.1.0"
edition = "2021"

[dependencies]
annotate-snippets = "0.11.4"
anyhow = "1.0.86"
clap = { version = "4.5.11", features = ["derive"] }
itertools = "0.13.0"
ropey = "1.6.1"
thiserror = "1.0.63"
tree-sitter = "0.22.6"
tree-sitter-wesl = { path = "../tree-sitter-wesl" }
unicode-ident = "1.0.12"
winnow = { version = "0.6.18" } # , features = ["debug"]
lalrpop-util = { version = "0.20.2", features = ["lexer", "unicode"] }

[build-dependencies]
lalrpop = "0.20.2"
