[workspace]
members = [
    "crates/wgsl-parse",
    "crates/wesl-macros",
    "crates/wesl",
    "crates/wesl-test",
    "crates/wesl-web",
    "crates/wesl-cli",
    "crates/tokrepr",
    "crates/tokrepr-derive",
    "examples/random_wgsl",
    "examples/wesl-consumer",
]

resolver = "3"

[workspace.package]
authors = ["WGSL Contributors", "Mathis Brossier <mathis.brossier@gmail.com>"]
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/wgsl-tooling-wg/wesl-rs"
version = "0.1.2"
rust-version = "1.87.0"

[workspace.dependencies]
wesl = { path = "crates/wesl", version = "0.1.2" }
wesl-macros = { path = "crates/wesl-macros", version = "0.1.2" }
wgsl-parse = { path = "crates/wgsl-parse", version = "0.1.2" }
tokrepr = { path = "crates/tokrepr", version = "0.0.1" }
tokrepr-derive = { path = "crates/tokrepr-derive", version = "0.0.1" }

[workspace.lints.rust]

[workspace.lints.clippy]
# TODO: change eventually
mutable_key_type = "allow"

[patch.crates-io]
wesl = { path = "crates/wesl" }

# [patch.'https://github.com/wgsl-tooling-wg/bevy-wgsl']
# bevy-wgsl = { path = "../bevy-wgsl" }
