[graph]
all-features = true

[advisories]
version = 2
ignore = [
  # See issue #69
  "RUSTSEC-2024-0320",
]

[licenses]
version = 2
allow = [
  "0BSD",
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "BSL-1.0",
  "CC0-1.0",
  "ISC",
  "MIT",
  "MIT-0",
  "Unlicense",
  "Zlib",
]

exceptions = []

[bans]
multiple-versions = "warn"
wildcards = "deny"

# Certain crates that we don't want multiple versions of in the dependency tree
deny = []

skip = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []

[[bans.features]]
# thiserror is the preferred way to derive error types
crate = "derive_more"
deny = ["error"]
