[package]
name = "d"
version = "0.1.0"
edition = "2024"

[dependencies]
wesl = { path = "../../../crates/wesl", features = ["package"] }

[build-dependencies]
wesl = { path = "../../../crates/wesl", features = ["package"] }
