[package]
name = "wesl-test"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
serde = { version = "1.0.210", features = ["derive"] }
wgsl-parse = { workspace = true }
wesl = { workspace = true, features = ["eval"] }
regex = "1.11.1"
libtest-mimic = "0.8.1"
serde_json = "1.0.140"

[lints]
workspace = true

[[test]]
name = "testsuite"
harness = false
