[package]
name = "wesl"
description = "The WESL rust compiler"
documentation = "https://docs.rs/wesl"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
annotate-snippets = "0.11.4"
bytes = "1.8.0"
derive_more = { version = "2.0.1", features = [
  "as_ref",
  "deref",
  "deref_mut",
  "display",
  "from",
  "unwrap",
] }
half = { version = "2.4.1", features = ["num-traits"] }
itertools = "0.14.0"
num-traits = "0.2.19"
serde = { version = "1.0.215", features = ["derive"], optional = true }
thiserror = "2.0.11"
wgsl-parse = { workspace = true, features = ["wesl"] }
wesl-macros = { workspace = true }
# deps for feature 'package'
proc-macro2 = { version = "1.0.93", optional = true }
quote = { version = "1.0.38", optional = true }

[features]
eval = []
generics = ["wgsl-parse/generics"]
serde = ["wgsl-parse/serde", "dep:serde"]
package = ["dep:proc-macro2", "dep:quote"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints]
workspace = true
