[package]
name = "a"
version = "0.1.0"
edition = "2024"

[dependencies]
wesl = { path = "../../../crates/wesl", features = ["package"] }
c = "0.1.0"
d = "0.1.0"

[build-dependencies]
wesl = { path = "../../../crates/wesl", features = ["package"] }
c = "0.1.0"
d = "0.1.0"
