[package]
name = "a"
version = "0.1.0"
edition = "2024"

[dependencies]
c = "0.1.0"
d = "0.1.0"
wesl = { path = "../../../crates/wesl", features = ["package"] }

[build-dependencies]
c = "0.1.0"
d = "0.1.0"
wesl = { path = "../../../crates/wesl", features = ["package"] }
