[package]
name = "c"
version = "0.1.1"
edition = "2024"

[dependencies]
wesl = { path = "../../../crates/wesl", features = ["package"] }

[build-dependencies]
wesl = { path = "../../../crates/wesl", features = ["package"] }
