[package]
name = "c"
version = "0.1.1"
edition = "2024"

[dependencies]
wesl = { features = ["package"], path = "../../../crates/wesl" }

[build-dependencies]
wesl = { features = ["package"], path = "../../../crates/wesl" }
