[package]
name = "b"
version = "0.1.0"
edition = "2024"

[dependencies]
c = "0.1.1"
d = "0.2.0"
wesl = { features = ["package"], path = "../../../crates/wesl" }

[build-dependencies]
c = "0.1.1"
d = "0.2.0"
wesl = { features = ["package"], path = "../../../crates/wesl" }
