[package]
name = "d"
version = "0.2.0"
edition = "2024"

[dependencies]
wesl = { features = ["package"], path = "../../../crates/wesl" }

[build-dependencies]
wesl = { features = ["package"], path = "../../../crates/wesl" }
