name: Dependencies

# Based on https://github.com/bevyengine/bevy/blob/main/.github/workflows/dependencies.yml

on:
  pull_request:
    paths:
      - "**/Cargo.toml"
      - "deny.toml"
  push:
    paths:
      - "**/Cargo.toml"
      - "deny.toml"
    branches:
      - main

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: ${{github.event_name == 'pull_request'}}

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: EmbarkStudios/cargo-deny-action@v2
